<?php
namespace R3alst\LaravelMagentoTwoConnector\Helper;

use Illuminate\Support\Str;
use R3alst\LaravelMagentoTwoConnector\Models\ModuleArtifact;

class Magento2Helper
{
    /**
     * @return string[]
     */
    public function getDefaultAcl() {
        return [
            "Magento_Customer::customer",
            "Magento_Log::online",
            "Magento_Sales::sales",
            "Magento_Sales::sales_operation",
            "Magento_Sales::sales_order",
            "Magento_Sales::actions",
            "Magento_Sales::reorder",
            "Magento_Catalog::catalog",
            "Magento_Catalog::catalog_inventory",
            "Magento_Catalog::products"
        ];
    }

    public function getBasicAclList() {
        return [
            "Dotdigitalgroup_Chat::config",
            "Dotdigitalgroup_Email::abandoned",
            "Dotdigitalgroup_Email::automation",
            "Dotdigitalgroup_Email::automation_enrollment",
            "Dotdigitalgroup_Email::automation_studio",
            "Dotdigitalgroup_Email::campaign",
            "Dotdigitalgroup_Email::catalog",
            "Dotdigitalgroup_Email::config",
            "Dotdigitalgroup_Email::contact",
            "Dotdigitalgroup_Email::cron",
            "Dotdigitalgroup_Email::dashboard",
            "Dotdigitalgroup_Email::exclusion_rules",
            "Dotdigitalgroup_Email::importer",
            "Dotdigitalgroup_Email::logviewer",
            "Dotdigitalgroup_Email::order",
            "Dotdigitalgroup_Email::reports",
            "Dotdigitalgroup_Email::review",
            "Dotdigitalgroup_Email::wishlist",
            "Dotdigitalgroup_Sms::config",
            "Dotdigitalgroup_Sms::report",
            "Dotdigitalgroup_Sms::reports",
            "Klarna_Core::system_logging",
            "Klarna_Core::system_support_form",
            "Magento_AdminNotification::adminnotification",
            "Magento_AdminNotification::adminnotification_remove",
            "Magento_AdminNotification::mark_as_read",
            "Magento_AdminNotification::show_list",
            "Magento_AdminNotification::show_toolbar",
            "Magento_AdobeIms::actions",
            "Magento_AdobeIms::adobe_ims",
            "Magento_AdobeIms::login",
            "Magento_AdobeIms::logout",
            "Magento_AdobeStockAsset::actions",
            "Magento_AdobeStockAsset::actions_delete",
            "Magento_AdobeStockAsset::actions_get",
            "Magento_AdobeStockAsset::actions_save",
            "Magento_AdobeStockAsset::actions_view",
            "Magento_AdobeStockAsset::adobe_stock_asset",
            "Magento_AdobeStockImageAdminUi::license_images",
            "Magento_AdobeStockImageAdminUi::media_gallery",
            "Magento_AdobeStockImageAdminUi::save_preview_images",
            "Magento_Analytics::advanced_reporting",
            "Magento_Analytics::analytics",
            "Magento_Analytics::analytics_api",
            "Magento_Analytics::analytics_settings",
            "Magento_Analytics::bi_essentials",
            "Magento_Analytics::business_intelligence",
            "Magento_Backend::additional_cache_management",
            "Magento_Backend::admin",
            "Magento_Backend::all",
            "Magento_Backend::cache",
            "Magento_Backend::content",
            "Magento_Backend::content_elements",
            "Magento_Backend::content_translation",
            "Magento_Backend::convert",
            "Magento_Backend::custom",
            "Magento_Backend::dashboard",
            "Magento_Backend::design",
            "Magento_Backend::extensions",
            "Magento_Backend::flush_cache_storage",
            "Magento_Backend::flush_catalog_images",
            "Magento_Backend::flush_js_css",
            "Magento_Backend::flush_magento_cache",
            "Magento_Backend::flush_static_files",
            "Magento_Backend::global_search",
            "Magento_Backend::local",
            "Magento_Backend::main_actions",
            "Magento_Backend::marketing",
            "Magento_Backend::marketing_communications",
            "Magento_Backend::marketing_seo",
            "Magento_Backend::marketing_user_content",
            "Magento_Backend::mass_actions",
            "Magento_Backend::myaccount",
            "Magento_Backend::refresh_cache_type",
            "Magento_Backend::schedule",
            "Magento_Backend::store",
            "Magento_Backend::stores",
            "Magento_Backend::stores_attributes",
            "Magento_Backend::stores_other_settings",
            "Magento_Backend::stores_settings",
            "Magento_Backend::system",
            "Magento_Backend::system_other_settings",
            "Magento_Backend::toggling_cache_type",
            "Magento_Backend::tools",
            "Magento_Backup::backup",
            "Magento_Backup::rollback",
            "Magento_Cart::cart",
            "Magento_Cart::manage",
            "Magento_Catalog::attributes_attributes",
            "Magento_Catalog::catalog",
            "Magento_Catalog::catalog_inventory",
            "Magento_Catalog::categories",
            "Magento_Catalog::config_catalog",
            "Magento_Catalog::edit_category_design",
            "Magento_Catalog::edit_product_design",
            "Magento_Catalog::products",
            "Magento_Catalog::sets",
            "Magento_Catalog::update_attributes",
            "Magento_CatalogInventory::cataloginventory",
            "Magento_CatalogRule::promo",
            "Magento_CatalogRule::promo_catalog",
            "Magento_CatalogSearch::config_catalog_search",
            "Magento_Checkout::checkout",
            "Magento_CheckoutAgreements::checkoutagreement",
            "Magento_Cms::block",
            "Magento_Cms::config_cms",
            "Magento_Cms::media_gallery",
            "Magento_Cms::page",
            "Magento_Cms::page_delete",
            "Magento_Cms::save",
            "Magento_Cms::save_design",
            "Magento_Config::advanced",
            "Magento_Config::config",
            "Magento_Config::config_admin",
            "Magento_Config::config_design",
            "Magento_Config::config_general",
            "Magento_Config::config_system",
            "Magento_Config::currency",
            "Magento_Config::dev",
            "Magento_Config::sendfriend",
            "Magento_Config::trans_email",
            "Magento_Config::web",
            "Magento_Contact::contact",
            "Magento_CurrencySymbol::currency_rates",
            "Magento_CurrencySymbol::symbols",
            "Magento_CurrencySymbol::system_currency",
            "Magento_Customer::actions",
            "Magento_Customer::config_customer",
            "Magento_Customer::customer",
            "Magento_Customer::delete",
            "Magento_Customer::group",
            "Magento_Customer::invalidate_tokens",
            "Magento_Customer::manage",
            "Magento_Customer::online",
            "Magento_Customer::reset_password",
            "Magento_Downloadable::downloadable",
            "Magento_Email::template",
            "Magento_EncryptionKey::crypt_key",
            "Magento_GoogleAnalytics::google",
            "Magento_ImportExport::export",
            "Magento_ImportExport::history",
            "Magento_ImportExport::import",
            "Magento_Indexer::changeMode",
            "Magento_Indexer::index",
            "Magento_Indexer::invalidate",
            "Magento_Integration::extensions",
            "Magento_Integration::integrations",
            "Magento_InventoryApi::inventory",
            "Magento_InventoryApi::source",
            "Magento_InventoryApi::source_edit",
            "Magento_InventoryApi::stock",
            "Magento_InventoryApi::stock_delete",
            "Magento_InventoryApi::stock_edit",
            "Magento_InventoryApi::stock_source_link",
            "Magento_InventoryInStorePickupApi::inStorePickup",
            "Magento_InventoryInStorePickupApi::notify_orders_are_ready_for_pickup",
            "Magento_InventorySalesApi::stock",
            "Magento_Logging::magento_logging",
            "Magento_Logging::magento_logging_events",
            "Magento_Logging::system_magento_logging_bulk_operations",
            "Magento_LoginAsCustomer::allow_shopping_assistance",
            "Magento_LoginAsCustomer::config_section",
            "Magento_LoginAsCustomer::login",
            "Magento_LoginAsCustomerLog::login_log",
            "Magento_MediaGalleryUiApi::create_folder",
            "Magento_MediaGalleryUiApi::delete_assets",
            "Magento_MediaGalleryUiApi::delete_folder",
            "Magento_MediaGalleryUiApi::edit_assets",
            "Magento_MediaGalleryUiApi::insert_assets",
            "Magento_MediaGalleryUiApi::upload_assets",
            "Magento_Multishipping::config_multishipping",
            "Magento_NewRelicReporting::config_newrelicreporting",
            "Magento_Newsletter::newsletter",
            "Magento_Newsletter::problem",
            "Magento_Newsletter::queue",
            "Magento_Newsletter::subscriber",
            "Magento_Newsletter::template",
            "Magento_PageBuilder::template_apply",
            "Magento_PageBuilder::template_delete",
            "Magento_PageBuilder::template_save",
            "Magento_PageBuilder::templates",
            "Magento_Payment::payment",
            "Magento_Payment::payment_services",
            "Magento_Paypal::actions_manage",
            "Magento_Paypal::authorization",
            "Magento_Paypal::billing_agreement",
            "Magento_Paypal::billing_agreement_actions",
            "Magento_Paypal::billing_agreement_actions_view",
            "Magento_Paypal::fetch",
            "Magento_Paypal::paypal",
            "Magento_Paypal::paypal_settlement_reports",
            "Magento_Paypal::paypal_settlement_reports_view",
            "Magento_Paypal::use",
            "Magento_Persistent::persistent",
            "Magento_ReCaptchaUi::config",
            "Magento_Reports::abandoned",
            "Magento_Reports::accounts",
            "Magento_Reports::bestsellers",
            "Magento_Reports::coupons",
            "Magento_Reports::customers",
            "Magento_Reports::customers_orders",
            "Magento_Reports::downloads",
            "Magento_Reports::invoiced",
            "Magento_Reports::lowstock",
            "Magento_Reports::product",
            "Magento_Reports::refunded",
            "Magento_Reports::report",
            "Magento_Reports::report_marketing",
            "Magento_Reports::report_products",
            "Magento_Reports::report_search",
            "Magento_Reports::reports",
            "Magento_Reports::review",
            "Magento_Reports::review_customer",
            "Magento_Reports::review_product",
            "Magento_Reports::salesroot",
            "Magento_Reports::salesroot_sales",
            "Magento_Reports::shipping",
            "Magento_Reports::shopcart",
            "Magento_Reports::sold",
            "Magento_Reports::statistics",
            "Magento_Reports::statistics_refresh",
            "Magento_Reports::tax",
            "Magento_Reports::totals",
            "Magento_Reports::viewed",
            "Magento_Review::pending",
            "Magento_Review::ratings",
            "Magento_Review::reviews_all",
            "Magento_Rss::rss",
            "Magento_Sales::actions",
            "Magento_Sales::actions_edit",
            "Magento_Sales::actions_view",
            "Magento_Sales::cancel",
            "Magento_Sales::capture",
            "Magento_Sales::comment",
            "Magento_Sales::config_sales",
            "Magento_Sales::create",
            "Magento_Sales::creditmemo",
            "Magento_Sales::email",
            "Magento_Sales::emails",
            "Magento_Sales::hold",
            "Magento_Sales::invoice",
            "Magento_Sales::order_statuses",
            "Magento_Sales::reorder",
            "Magento_Sales::review_payment",
            "Magento_Sales::sales",
            "Magento_Sales::sales_creditmemo",
            "Magento_Sales::sales_email",
            "Magento_Sales::sales_invoice",
            "Magento_Sales::sales_operation",
            "Magento_Sales::sales_order",
            "Magento_Sales::sales_pdf",
            "Magento_Sales::ship",
            "Magento_Sales::shipment",
            "Magento_Sales::transactions",
            "Magento_Sales::transactions_fetch",
            "Magento_Sales::unhold",
            "Magento_SalesRule::config_promo",
            "Magento_SalesRule::quote",
            "Magento_Search::search",
            "Magento_Search::synonyms",
            "Magento_Securitytxt::config",
            "Magento_Shipping::carriers",
            "Magento_Shipping::config_shipping",
            "Magento_Shipping::shipping_policy",
            "Magento_Sitemap::config_sitemap",
            "Magento_Sitemap::sitemap",
            "Magento_Swatches::iframe",
            "Magento_Tax::config_tax",
            "Magento_Tax::manage_tax",
            "Magento_TaxImportExport::import_export",
            "Magento_Theme::theme",
            "Magento_TwoFactorAuth::config",
            "Magento_TwoFactorAuth::tfa",
            "Magento_UrlRewrite::urlrewrite",
            "Magento_User::acl",
            "Magento_User::acl_roles",
            "Magento_User::acl_users",
            "Magento_User::locks",
            "Magento_Variable::variable",
            "Magento_Widget::widget_instance",
            "Magento_Wishlist::config_wishlist",
            "PayPal_Braintree::settlement_report",
            "Yotpo_Core::config",
            "Yotpo_Yotpo::config",
            "Yotpo_Yotpo::yotpo_analytics_external",
            "Yotpo_Yotpo::yotpo_report_reviews",
            "Yotpo_Yotpo::yotpo_reviews_external"
        ];
    }

    public function createModuleFromOptions($options = [], $logArtifact = true) {
        $_options = array_merge([
            "vendor" => "R3alst",
            "moduleName" => "Integration",
            "integrationName" => "r3alstIntegration",
            "contactEmail" => "r3alst@gmail.com",
            "endpointUrl" => "https://m2connector.modsolutionz.com/api/magento2/v1/oauth/callback",
            "identityUrl" => "https://m2connector.modsolutionz.com/magento2/login",
            "resourcesList" => $this->getDefaultAcl()
        ], $options);

        $resourcesList = "";
        foreach ($_options["resourcesList"] as $resource) {
            $resourcesList .= "<resource name=\"" . $resource . "\"/>\n";
        }
        $zipFileName = Str::random(40) . ".zip";
        $zipArchive = new \ZipArchive();
        $zipArchive->open($zipFileName, \ZipArchive::CREATE | \ZipArchive::OVERWRITE);
        $moduleBasePath = $_options["vendor"] . "/" . $_options["moduleName"];
        $moduleFiles = [
            [
                "destination" => $moduleBasePath . "/registration.php",
                "source" => __DIR__ . "/../../stubs/registration.php.stub"
            ],
            [
                "destination" => $moduleBasePath . "/etc/module.xml",
                "source" => __DIR__ . "/../../stubs/module.xml.stub"
            ],
            [
                "destination" => $moduleBasePath . "/etc/integration/api.xml",
                "source" => __DIR__ . "/../../stubs/api.xml.stub"
            ],
            [
                "destination" => $moduleBasePath . "/etc/integration/config.xml",
                "source" => __DIR__ . "/../../stubs/config.xml.stub"
            ],
            [
                "destination" => $moduleBasePath . "/Setup/InstallData.php",
                "source" => __DIR__ . "/../../stubs/InstallData.php.stub"
            ]
        ];
        foreach ($moduleFiles as $moduleFile) {
            $zipArchive->addFromString($moduleFile["destination"], str_replace(
                ["{{vendor}}", "{{moduleName}}", "{{integrationName}}", "{{resourceList}}", "{{contactEmail}}", "{{endpointUrl}}", "{{identityUrl}}"],
                [$_options["vendor"], $_options["moduleName"], $_options["integrationName"], $resourcesList, $_options["contactEmail"], $_options["endpointUrl"], $_options["identityUrl"]],
                \file_get_contents($moduleFile["source"])
            ));
        }
        $zipArchive->close();
        if($logArtifact) {
            $moduleArtifact = new ModuleArtifact();
            $moduleArtifact->fill([
                "zip_filename" => $zipFileName,
                "options" => $_options
            ]);
            $moduleArtifact->save();
        }
        return $zipFileName;
    }
}